#!/usr/bin/env node
// Writes the accent palette (src/lib/core/values.ts → ACCENTS) as CSS custom properties, so
// stylesheets can use a palette colour without spelling it:
//
//   node scripts/build-palette.mjs           write src/lib/styles/palette.css
//   node scripts/build-palette.mjs --check   exit 1 if the file is out of date
//
// The properties are namespaced (--fl-accent-<id>) so they cannot collide with a consumer's.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ACCENTS } from '../src/lib/core/values.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src/lib/styles/palette.css');

const css = `/*
 * The accent palette as custom properties. Generated by scripts/build-palette.mjs from ACCENTS in
 * src/lib/core/values.ts: do not edit. Change the palette there and rebuild.
 */
:root {
${ACCENTS.map((accent) => `\t--fl-accent-${accent.id}: ${accent.value};`).join('\n')}
}
`;

if (process.argv.includes('--check')) {
	let current = '';

	try {
		current = readFileSync(out, 'utf8');
	} catch {
		/* missing counts as out of date */
	}

	if (current !== css) {
		console.error('[palette] src/lib/styles/palette.css is out of date: run `pnpm palette:build`');
		process.exit(1);
	}

	console.log(`[palette] palette.css matches the ${ACCENTS.length} accents`);
} else {
	writeFileSync(out, css);
	console.log(`[palette] ${ACCENTS.length} accents → src/lib/styles/palette.css`);
}
